### ISSUE TITLE
show-proxied-endpoints does not list grafana

### ISSUE THREAD

**Issue by nishant-dash** [canonical/traefik-k8s-operator#218]
### Bug Description

When I run the traefik action `show-proxied-endpoints`, it does not list grafana as one of them

```console
$ juju run-action traefik/0 --wait show-proxied-endpoints | yq '."unit-traefik-0".results."proxied-endpoints"' | jq
{
  "prometheus/0": {
    "url": "http://<IP>:<PORT>/cos-prometheus-0"
  },
  "loki/0": {
    "url": "http://<IP>:<PORT>/cos-loki-0"
  },
  "catalogue": {
    "url": "http://<IP>:<PORT>/cos-catalogue"
  },
  "alertmanager": {
    "url": "http://<IP>:<PORT>cos-alertmanager"
  }
}
```

### To Reproduce

1. Run the `show-proxied-endpoints` action on traefik

### Environment

Tested against - stable, 110

### Relevant log output

```shell
N/A
```

**Comment by sed-i** [comment]
That is correct. Since grafana comes in via [traefik-route](https://github.com/canonical/traefik-route-k8s-operator/blob/main/lib/charms/traefik_route_k8s/v0/traefik_route.py), there is no easy way to include it in the list.

We were considering a dedicated [ingress-per-leader](https://github.com/canonical/traefik-k8s-operator/pull/180) lib that would solve this, but that effort was discontinued.

Workarounds:
- `juju show-unit grafana/0 | grep "url:"`
- `juju ssh --container catalogue cat/0 cat /web/config.json | jq '.apps'`
- The grafana equivalent of `juju ssh am/0 PEBBLE_SOCKET=/charm/containers/alertmanager/pebble.socket /charm/bin/pebble plan | yq '.services.alertmanager.command'`

**Comment by dstathis** [comment]
Closing for now. If you still need this, feel free to reopen.
